language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo 
addons:
  mariadb: '10.2'
before_install:
  - mysql -e 'SET GLOBAL max_connections = 400;'
  - mysql -e 'DROP DATABASE IF EXISTS test;'
  - mysql -e 'CREATE DATABASE test;'
env:
  - TEST_DB_USER=root
before_cache:
  - rm -f ~/.cargo/registry/lock
  - rm -r target/debug/config
  - rm -r target/debug/log
script:
  - cargo build --verbose
  - mysql -e 'DROP DATABASE IF EXISTS test;'
  - mysql -e 'CREATE DATABASE test;'
  - RUST_BACKTRACE=1 cargo test -- --test-threads=1
  - mysql -e 'DROP DATABASE IF EXISTS test;'
  - mysql -e 'CREATE DATABASE test;'
# init config
  - cargo run --bin clantool -- --help || true
  - sed -i -e 's/"user"/"root"/g' target/debug/config/config.toml
  - sed -i -e 's/password = "password"//g' target/debug/config/config.toml
  - sed -i -e 's/"clantool"/"test"/g' target/debug/config/config.toml
  - cat target/debug/config/config.toml
# init conifg ranked_daemon, looks for config in run-dir
  - cp ranked/ctd_config.toml ctd_config.toml
  - sed -i -e 's/"ctd"/"root"/g' ctd_config.toml
  - sed -i -e 's/password = "password"//g' ctd_config.toml
  - sed -i -e 's/"clantool"/"test"/g' ctd_config.toml
  - cat ctd_config.toml
# init db & run crawl
  - RUST_BACKTRACE=1 cargo run --bin clantool -- init
  - RUST_BACKTRACE=1 cargo run --bin clantool -- fcrawl
  - RUST_BACKTRACE=1 cargo run --bin ranked_daemon -- -c --no-daemon
  - mysql -e 'DROP DATABASE test;'
