language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo 
addons:
  mariadb: '10.2'
before_install:
  - mysql -e 'SET GLOBAL max_connections = 400;'
  - mysql -e 'DROP DATABASE IF EXISTS test;'
  - mysql -e 'CREATE DATABASE test;'
env:
  - TEST_DB_USER=root
before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
  - rm -f ~/.cargo/registry/lock
  - rm -rf config
  - rm -rf log
script:
  - bash test.sh
